DELETE FROM states;
DELETE FROM skill;

INSERT INTO states (code, state) VALUES
('AL', 'Alabama'),
('AK', 'Alaska'),
('AZ', 'Arizona'),
('AR', 'Arkansas'),
('CA', 'California'),
('CO', 'Colorado'),
('CT', 'Connecticut'),
('DE', 'Delaware'),
('FL', 'Florida'),
('GA', 'Georgia'),
('HI', 'Hawaii'),
('ID', 'Idaho'),
('IL', 'Illinois'),
('IN', 'Indiana'),
('IA', 'Iowa'),
('KS', 'Kansas'),
('KY', 'Kentucky'),
('LA', 'Louisiana'),
('ME', 'Maine'),
('MD', 'Maryland'),
('MA', 'Massachusetts'),
('MI', 'Michigan'),
('MN', 'Minnesota'),
('MS', 'Mississippi'),
('MO', 'Missouri'),
('MT', 'Montana'),
('NE', 'Nebraska'),
('NV', 'Nevada'),
('NH', 'New Hampshire'),
('NJ', 'New Jersey'),
('NM', 'New Mexico'),
('NY', 'New York'),
('NC', 'North Carolina'),
('ND', 'North Dakota'),
('OH', 'Ohio'),
('OK', 'Oklahoma'),
('OR', 'Oregon'),
('PA', 'Pennsylvania'),
('RI', 'Rhode Island'),
('SC', 'South Carolina'),
('SD', 'South Dakota'),
('TN', 'Tennessee'),
('TX', 'Texas'),
('UT', 'Utah'),
('VT', 'Vermont'),
('VA', 'Virginia'),
('WA', 'Washington'),
('WV', 'West Virginia'),
('WI', 'Wisconsin'),
('WY', 'Wyoming');


INSERT INTO skill (id, name) VALUES
(1, 'Database Management'),
(2, 'IT Proficiency'),
(3, 'Website Management'),
(4, 'Project Management'),
(5, 'Time Management'),
(6, 'Budgeting'),
(7, 'Communication'),
(8, 'Teamwork'),
(9, 'Problem-Solving'),
(10, 'Fundraising'),
(11, 'Grant Writing'),
(12, 'Policy and Advocacy'),
(13, 'Leadership'),
(14, 'Adaptability'),
(15, 'Ethical Awareness'),
(16, 'Empathy'),
(17, 'Cultural Competence'),
(18, 'Resilience');
